export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const FETCH_ALL_CHANNELS_LOADING = 'FETCH_ALL_CHANNELS_LOADING'
export const FETCH_ALL_CHANNELS_SUCCESS = 'FETCH_ALL_CHANNELS_SUCCESS'
export const FETCH_ALL_CHANNELS_ERROR = 'FETCH_ALL_CHANNELS_ERROR'

export const CREATE_CHANNEL_LOADING = 'CREATE_CHANNEL_LOADING'
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS'
export const CREATE_CHANNEL_ERROR = 'CREATE_CHANNEL_ERROR'

export const FETCH_CHANNEL_LOADING = 'FETCH_CHANNEL_LOADING'
export const FETCH_CHANNEL_SUCCESS = 'FETCH_CHANNEL_SUCCESS'
export const FETCH_CHANNEL_ERROR = 'FETCH_CHANNEL_ERROR'

export const ADD_MEMBER_TO_CHANNEL_LOADING = 'ADD_MEMBER_TO_CHANNEL_LOADING'
export const ADD_MEMBER_TO_CHANNEL_SUCCESS = 'ADD_MEMBER_TO_CHANNEL_SUCCESS'
export const ADD_MEMBER_TO_CHANNEL_ERROR = 'ADD_MEMBER_TO_CHANNEL_ERROR'

export const ADD_MESSAGE_LOADING = 'ADD_MESSAGE_LOADING'
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS'
export const ADD_MESSAGE_ERROR = 'ADD_MESSAGE_ERROR'

export const IS_LOADING = 'IS_LOADING';
export const IS_SUCCESS = 'IS_SUCCESS';
export const IS_FAILURE = 'IS_FAILURE';